### ISSUE TITLE
LD matrix calculations

### ISSUE THREAD

**Issue by npanousis** [jrs95/gassocplot2#2]
Hello,
Thank you for providing the code for these plots. This is not a bug report but more a question.
How do you calculate the correlation matrix with LDlink since the API allows only 1000 variants? Any help would be appreciated. 

Thanks a lot,
Nikos

**Comment by jrs95** [comment]
Hi Nikos,

Yes, this can be a problem for larger regions.

Perhaps the IEU GWAS R [ld_matrix function](https://github.com/mrcieu/ieugwasr) could do the trick. Although, if you are wanting to plot a lot of regional plots you might be better off downloading the 1000G VCFs and writing a small script to compute the LD.

Best wishes,

James
