### ISSUE TITLE
plot_assoc function uses undefined variable "markers"

### ISSUE THREAD

**Issue by florianbay** [jrs95/gassocplot2#3]
If no correlation matrix is given, the function uses nrow(markers). I think it should be nrow(data).

`if(is.null(corr)` & is.null(corr.top)){r2_legend <- FALSE; corr <- matrix(NA, nrow=nrow(markers), ncol=nrow(markers))}`

**Comment by jrs95** [comment]
Hi,

Thanks very much for spotting this issue, it has now been fixed.

Best wishes,

James
