### ISSUE TITLE
Is it handy to suppress the titles from each panel?

### ISSUE THREAD

**Issue by jinghuazhao** [jrs95/gassocplot2#4]
Dear James,

Before I make a mess of the cloned codes, I am wondering if it is handy to suppress the titles associated with each panel, (giving names "" would not remove the inter-panel space) for we have many plots to stack so as to save space -- if the titles could be put inside the plot it would even be better!

Many thanks for creating such as useful package which we used a lot.

Jing Hua

**Comment by jrs95** [comment]
Hi Jing Hau,

Apologies for the delayed response.

Good suggestion. I am not planning on making any more updates to gassocplot2. However, I am hoping to release a new package called GENI plots within the next few months which will include a static/interactive region plot, alongside other plots commonly used in genetics. So, I will keep this suggestion in mind for that.

Best wishes,

James
